### ISSUE TITLE
Decide on npm organization and create

### ISSUE THREAD

**Issue by ptrthomas** [jbangdev/jbang-npm#2]
@maxandersen I've created the first version. I think it is best you create the NPM organization or I'm not sure if a simple "jbang" as the package name is still possible or preferable.

Other things to decide: OSS License ?

I had tried installing on Windows Server (AWS) and it worked. That said, some CI testing on different OS-es may be needed. Already got one bug report: https://github.com/karatelabs/karate-npm/issues/1 

I could not figure out how to provide a download status on the console, so it does seem like `npm install` hangs when downloading the JDK, large binaries etc.

Note that NPM preinstall hooks has a quirk, it doesn't work when installing in some ways: https://stackoverflow.com/a/63238108/143475

**Comment by maxandersen** [comment]
Sweet. I have publish/unpublish rights for single named jbang but also jbangdev org. I'm leaning towards using jbangdev/jbang and deprecate the others but not sure if I can do that without opening up use of jbang in future. 

I'll check.

**Comment by ptrthomas** [comment]
@maxandersen I think if you create a bare-bones NPM project locally and publish it - you can "claim" the `jbang` name.

much to my annoyance, I found someone squatting on `karate` already: https://www.npmjs.com/package/karate

**Comment by maxandersen** [comment]
All done.
